#---
#- name: Configure NTP server on ping host
#  hosts: ping
#  roles:
#    - synchronization-setup
#
#- name: Configure NTP client on pong host
#  hosts: pong
#  roles:
#    - synchronization-setup

- name: Run experiment on all hosts
  hosts: all
  become: yes
  roles:
    - experiment