---
- name: Configure NTP/Chrony server
  ansible.builtin.template:
    src: 'chrony_server.conf.j2'
    dest: '/etc/chrony/chrony.conf'
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart NTP service
  become: true


- name: Debug check mode state
  ansible.builtin.debug:
    msg: "Check mode is {{ ansible_check_mode }}"
- name: Enable and start NTP service
  ansible.builtin.service:
    name:  'chronyd'
    state: started
    enabled: true
  when: ansible_check_mode == false

- name: Wait for chrony service to start
  wait_for:
    timeout: 10
    delay: 2

- name: Capture server synchronization status
  shell: "chronyc tracking"
  register: server_tracking

- name: Display server synchronization status
  debug:
    msg: "{{ server_tracking.stdout }}"