---
# tasks file for roles/synchronization-setup
- name: Install NTP
  apt:
    name: ntp
    state: present
  become: true

- name: Configure NTP
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp
  become: true

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
    enabled: true
  become: true


