---
# tasks file for roles/prometheus
---
- name: Install Prometheus
  apt:
    name: prometheus
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Install Prometheus
  zypper:
    name: prometheus
    state: present
  become: yes
  when: ansible_os_family == "SUSE"

- name: Configure Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  become: yes

- name: Ensure Prometheus is running
  service:
    name: prometheus
    state: started
    enabled: yes
  become: yes

